version: "3.9"
services:
# ------------------------------ Angular
  web:
    networks:
      frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Angular
    restart: unless-stopped
    image: goodfood-web:latest
    ports:
      - "4200:80"
      # - "49153:49153"
    # volumes:
    #  - ../app:/app
# ------------------------------ Compodoc
  compodoc:
    networks:
      frontend:
    build:
      context: ./
      dockerfile: ./documentation/Dockerfile
    container_name: Compodoc
    restart: unless-stopped
    image: goodfood-compodoc
    working_dir: /documentation
    volumes:
      - ./:/documentation
    ports:
      - "4242:4201"

networks:
  frontend:
    driver: bridge
