version: "3.9"
services:
# ------------------------------ Angular
  web:
    networks:
      frontend:
    container_name: Angular
    image: goodfood-web
    ports:
      - "4200:4200"
# ------------------------------ Compodoc
  compodoc:
    networks:
      frontend:
    build:
      context: ./
      dockerfile: ./documentation/Dockerfile
    container_name: Compodoc
    image: goodfood-compodoc
    working_dir: /documentation
    volumes:
      - ./:/documentation
    ports:
      - "4242:4201"
# ------------------------------ Jenkins
  jenkins:
    networks:
      frontend:
    container_name: Jenkins
    image: jenkins/jenkins:lts-jdk11
    user: jenkins
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
# ------------------------------ SonarQube
  sonarqube:
    networks:
      frontend:
    platform: linux/x86_64 #Put this line in comment for your case
    container_name: Sonarqube
    image: sonarqube:8.9.7-community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9090:9000"

networks: 
  frontend:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: