version: "3.9"
services:
  # ------------------------------ Angular
  web:
    networks:
      goodfood:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Angular
    restart: unless-stopped
    image: goodfood-web:latest
    ports:
      - "4200:80"
      # volumes:
      #  - ../app:/app
    volumes:
      - .:/app:cached
  # ------------------------------ Compodoc
  compodoc:
    networks:
      goodfood:
    build:
      context: ./
      dockerfile: ./documentation/Dockerfile
    container_name: Compodoc
    restart: unless-stopped
    image: goodfood-compodoc
    working_dir: /documentation
    volumes:
      - ./:/documentation
    ports:
      - "4242:4201"

networks:
  goodfood:
    driver: bridge
