name: SonarCloud Scan
on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      # Setup of NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test:headless

      - name: Build
        run: npm run build

      - name: Display the path
        run: echo $PATH
        shell: typescript

      - name: Coverage paths
        working-directory: coverage/lcov-report
        run: |
          sed -i 's/\/home\/runner\/work\//\/github\/workspace\//g' lcov.info
        #sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' sonar-cloud-reporter.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          path: coverage/lcov-report/coverage-summary.json
          title: Karma Test Coverage

      - run: echo "This job's status is ${{ job.status }}. 🚀 "
